title: Little Jamaica Blog
description: Little Jamaica Blog
baseurl: ""
url: "localhost:4000"

collections:
- shows

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
